author = 'Example Plugin'
description = 'Example Plugin'
version = '1.0.0'

server_scripts = {
    "../INITIALIZATION/loadlibs.lua",
    "../objects/Action.lua",
    "../objects/Command.lua", 
    "../objects/Infos.lua",
    "../objects/Role.lua",
    "../objects/RoleAction.lua",
    "../objects/RoleCommand.lua",
    "../objects/User.lua",
    "../objects/UserIp.lua",
    "../objects/UserRole.lua",
    "../objects/UserStatus.lua",
    "../repositories/UserRepository.lua",
    "../repositories/UserStatusRepository.lua",
    "../repositories/UserIpRepository.lua",
    "../repositories/RoleRepository.lua",
    "../repositories/UserRoleRepository.lua",
    "../repositories/ActionRepository.lua",
    "../repositories/CommandRepository.lua",
    "../repositories/RoleActionRepository.lua",
    "../repositories/RoleCommandRepository.lua",
    "../utils/misc.lua",
    "../main/config/Settings.lua",
    "../main/online.lua",
    "../database/sqlresultcode.lua",
    "../database/Database.lua",
    "../database/services/StatusService.lua",
    "../database/services/UsersService.lua", 
    "../database/services/UsersIpsService.lua",
    "../main/permissions/PermissionsHandler.lua",
    "../main/messages/MessagesHandler.lua",
    "../main/commands/CommandsHandler.lua",
    "../main/actions/ActionsHandler.lua",
    "../main/commands/all/*",
    "../main/actions/all/*",
    "../main/permissions/default.lua",
    "../main/registerPlayer.lua",
    "../main/events/dispatcher.lua",
    "../INITIALIZATION/main.lua",
}